# databases:
#   - name: moonevue-db
#     databaseName: moonevue
#     plan: free
#     type: postgres

services:
  - type: web
    name: moonevue-api
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    # Fix port binding
    port: 8080
    env: docker
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
