FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "exec", "next", "dev", "--turbopack", "-H", "0.0.0.0", "-p", "3000"]
